Repository Loki-Code201/foodwise, pull requests merged in 2021-08, with the labels that each got.

#21 Pantry initial structure setup
  index.html
  js/aboutUs.js
  js/pantry.js
  pantry.html
Labels: enhancement

#26 Pantry constructor
  js/pantry.js
  pantry.html
Labels: enhancement

#32 changed table hover so that it hovers entire rows
  css/style.css
  js/pantry.js
  pages/pantry.html
Labels: design, enhancement

#39 Render storage
  js/pantry.js
  pages/pantry.html
Labels: enhancement

#45 added background images to other pages and formatted layout and form …
  css/style.css
  images/GitHub-LinkedIn.jpg
  images/KasonBraley.jpg
  images/RahzaeWilliams.jpg
  images/RyanEmmans.jpg
  images/StefanieRiehle.jpg
  images/carts.jpg
  images/carts2.jpg
  images/github.png
  images/linked-in.png
  images/pantry.jpg
  images/pasta.jpg
  images/pasta2.jpg
  images/pasta3.jpg
  images/pasta4.jpg
  images/pasta5.jpg
  index.html
  pages/about.html
  pages/pantry.html
  pages/shopping-list.html
Labels: design

#56 Wed layout1
  css/style.css
  images/carts2.jpg
  images/pantryBG.jpg
  images/pasta5.jpg
  images/produce-table.jpg
  images/produce3.jpg
  images/produce4.jpg
  images/produceImage.jpg
  index.html
  pages/about.html
  pages/pantry.html
  pages/shopping-list.html
Labels: design, enhancement

#54 Table logic
  css/style.css
  js/pantry.js
  pages/pantry.html
Labels: enhancement

#60 form styling complete, only styling left is for tables
  css/style.css
  index.html
  pages/about.html
  pages/pantry.html
  pages/shopping-list.html
Labels: design

#64 added logo to header, plus other minor layout tweaks.
  css/style.css
  images/icons/delete-bin-line.png
  images/logo.png
  index.html
  pages/about.html
  pages/pantry.html
  pages/shopping-list.html
Labels: design

#59 Refactor: Abstracted functions
  js/pantry.js
Labels: enhancement

#75 Shopping list overhaul
  js/app.js
  js/pantry.js
  js/shoppinglist.js
  pages/pantry.html
  pages/shopping-list.html
Labels: enhancement

#80 Button updates, final styling tweaks
  css/style.css
  images/icons/blob.svg
  pages/about.html
Labels: design
